services:
  postgres:
    image: postgres:17
    container_name : url_shortener_postgres
    restart : unless-stopped

    environment:
      POSTGRES_USER: url_shortener
      POSTGRES_PASSWORD: url-shortner-dev-password
      POSTGRES_DB: url_shortener
    
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: